### ISSUE TITLE
기능 추가 제안: Java 기반 전자정부 프레임워크에서 Javascript 코드 호환 기능 추가

### ISSUE THREAD

**Issue by hmmhmmhm** [eGovFramework/egovframe-template-simple-backend#1]
## 기능 추가 제안

> 이 이슈는 기능 추가 제안 생성을 통한 검토요청이 가능할지 확인을 받고자 하는 이슈입니다.

### 💬  주 제안 내용 요약

Java 기반의 전자정부 프레임워크 백엔드 예시에서
Java 기반에서 Javascript 코드를 작성해서 확장할 수 있는
기능 예시를 만들어서 제안해보고 싶습니다.

제안에는 Javet 이라는 이미 개발된 모듈을 사용해보고자 하며
이 모듈은 Java 프로젝트에서 Javascript  코드를 실행시키고
Javascript 에서 Java 함수를 사용할 수 있게 만들어주는 기능을 가지고 있습니다.

해당 기능을 추가하는 PR을 생성하고 검토받을 수 있을지 확인을 부탁드립니다.

[참고자료: Javet internal structure](https://docs.google.com/presentation/d/1lQ8xIHuywuE0ydqm2w6xq8OeQZO_WeTLYXW9bNflQb8)
[참고자료: Javet official page](https://www.caoccao.com/Javet)

### 💡 제안 배경

전자정부 프레임워크의 백엔드 주요언어는 Java 이며
최근 Spring Boot 방식의 시도와 함께 앞단과 뒷단을 구분하는
예시를 제공하는 시도가 이뤄지고 있는 것으로 알고 있습니다.

최신 앞단 주요 예시는 Javascript 언어를 기반으로 예시가 구성되있으며
최신 앞단 주요 예시는 Java 언어를 기반으로 예시가 구성되있습니다.

앞단과 뒷단의 언어가 서로 상이하여 앞단 개발에서 사용된 로직이나 오픈소스를
뒷단 쪽에서도 사용하려할 경우 매번 두가지 언어로 동시에 개발해야하는 한계점이 있습니다.

그러나 이는 대체로 매우 많은 업무량을 만들게 되며, 이로 인해 많은 자바스크립트 오픈소스들을
전자정부 프레임워크 뒷단에서 사용하기 어렵게 만드는 한계점을 야기합니다.

### ✨ 제안하는 해결책

Java 기반의 프로젝트를 전부 Javascript 로
재작성하는 것은 엄청난 작업량이 소요되지만

Java 기반의 프로젝트에서 Javascript 코드를 주입해서
Java 함수를 사용할 수있게 하는 것은 매우 간단합니다.

Javet은 Java 프로젝트 에서 Node.js 와 V8 을 사용할 수 있게 만들어주는 모듈입니다.
이 모듈을 이용하면 Java 위에서 Javascript 코드를 실행시킬 수 있을 뿐만 아니라,
Javascript 코드에서 Java 로 짜여진 전자정부프레임워크의 기능들을 호출할 수도 있습니다.

### ✨ 제안 내용으로 인한 기대점

- 자바스크립트 기반의 오픈소스 모듈이나 로직을 뒷단에서도 사용가능하게 되어서,
앞단에서 사용되는 로직함수들을 매번 다시 자바로 재 작업하는 일이 줄어들 수 있습니다.

- 별도로 이를 위해 RESTFUL API 등을 별도로 만들어서 별개 MSA 서버로 구성하는 것보다,
작업량과 통신량을 크게 낮출 수 있으며 이로 인한 생산성 증가를 기대할 수 있습니다.

- 자바를 주 언어로 사용하지 않는 회사에도 Javascript 를 통한 전자정부 프레임워크
사용이 가능하게 하여 DX 를 크게 개선하고 접근성을 높이는 긍정적인 영향을 기대할 수 있습니다.

- 많은 예산을 투자하여 작업을 진행하지 않고도 여러 개발 프레임워크들을
호환할 수 있는 기회가 될 것이며, 점진적으로 전자정부 프레임워크의 확장성을 크게 높일 것입니다.

**Comment by Jeongyong-park** [comment]
Spring 기반의 전자정부 프레임워크를 사용하다가 한동안 SI기업이 아닌 다른 분야에서 Node.js 와 React로 구성된 프로젝트를 진행하면서 참 많은것을 느꼈습니다.

- 하나는 JSP뷰가 아닌 현대적 방식의 프론트 화면 개발시 실시간 핫스왑이 상당히 빠르다는 것.
- NPM, Yarn, 등의 생태계에서 정말 많은 라이브러리들이 금방금방 발전하고 나온다는점.
- 또 다른 하나는 github 내에서 Java보다 압도적으로 Javascript 프로젝트들이 많다는점.
 
NodeJS로 백엔드를 구성하고 React로 프론트로 구성하면서 Javascript(Typescript)로 공통의 라이브러리 함수들을 공유하는 방식으로 개발하면 동일한 언어로 인한 이점이 상당히 많았습니다.

과거 전자정부프레임워크로 작업할때 프론트는 jQuery, 백엔드는 Apache Common 라이브러리 나눠져있어서 동일한 기능도 백엔드 프론트엔드 별로 코드가 중복 개발되었던 기억이 있네요.

백엔드와 프론트엔드 둘다 외부 API를 사용하기위해서 하나의  동일한 fetch 함수 또는 Axios, GraphQL 라이브러리를 통해 동일한 함수로 처리할 수 있습니다.

타입의 정의와 규칙성을 강제화 하기위한 Typescript로 가야지 개발자와 유지보수자가 다를 경우에도 유지보수성이 용이할 것 같습니다.

**Comment by hmmhmmhm** [comment]
저도 그러한 방향이 좋을 것 같습니다, 전자정부 프레임워크 팀에서 그러한 방향으로 작업을 진행시켜주시면 너무 좋을것 같네요!

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 실시하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 소정의 기념품과 함께 표준프레임워크 오픈커뮤니티에서 커피쿠폰을 같이 발송 드릴 예정입니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by hmmhmmhm** [comment]
@eGovFrameSupport 입력하였습니다! 좋은 행사 감사합니다! 😀

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에 
대단히 감사드립니다.
