### ISSUE TITLE
API - UI 완전분리, 명명규칙 변경.

### ISSUE THREAD

**Issue by goodjwon** [eGovFramework/egovframe-template-simple-backend#10]
API 로 분리 및 RestDoc  등으로 실행 할 수 있는 환경으로 변경 했으면 합니다.
기존 구조에서 UI 관련 요소들은 최대한 배제 하고 API 안내 형태로 처리 했으면 좋겠습니다.
아마도 simple-backend 가 그런 의미로 만들어 지고 있는 것 같습니다만.. 
기존 논리적인 기능들은  유지하되 새로운 틀로 진행 했으면 좋지 않을까 합니다.
일부 호환성을 포기 하더라도 그렇게 하는게 좋지 않을까 싶습니다.
테스트 케이스 및 문서 자동화를 적극 활용하고 

명명규칙에 약자는 최대한 배재 하는게 좋겠습니다.
공공 프로젝트를 하셨던 분들은 그나마 접근이 좀 편 하실 수 있겠으나 처음에는 진입시에는 장벽이 있다고 생각 됩니다.
애써 만든 기능들을 여러사람들이 재활용 하기 편하게 한다면 좀더 많은 개발자 유입이 가능 하리라 봅니다.
업체 주도 프로젝트에서 진정한 오픈소스 프로젝트로 거듭나길 바래 봅니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 실시하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 소정의 기념품과 함께 표준프레임워크 오픈커뮤니티에서 커피쿠폰을 같이 발송 드릴 예정입니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에 
대단히 감사드립니다.
