### ISSUE TITLE
코딩 컨벤션을 정의하고 적용했으면 좋겠습니다.

### ISSUE THREAD

**Issue by DavidEugen** [eGovFramework/egovframe-template-simple-backend#12]
코딩 컨벤션의 경우 프로젝트를 하면서 지켜야 할 규칙들을 정하므로, 통일된 스타일 규칙을 통해 가독성을 높혀 코딩 효율성을 높일 수 있을 거라 생각합니다.
템플릿 뿐만 아니라 공통컴포넌트, 실행환경등 프로그램이 큰 만큼 소스별 다양한 개발 스타일들이 적용되어 있습니다.
이에 가독성도 떨어 질 뿐더러 재활용성이 떨어지는 경우가 있습니다.
이에 코딩 컨벤션을 정의하고 통일된 규칙을 적용하므로써 효율성을 높이도록 하면 좋겠습니다.

**Comment by eGovFrameSupport** [comment]
표준프레임워크에 대한 지속적인 참여에 
대단히 감사드립니다.
