### ISSUE TITLE
[기능요구(Feature)]: 

### ISSUE THREAD

**Issue by Chung10Kr** [eGovFramework/egovframe-template-simple-backend#20]
### 연락처 Contact

chung10@kakao.com

### 추가 요청 기능명 Feature Name

비밀번호 문의

### 기능 상세 설명 Feature Description

로그인할때 셋팅되어 있는 ID/PWD 관련해서 문서가 없는듯 한데
초기에 로그인 할 수 있는 계정이 따로 있을까요?

**Comment by eGovFrameSupport** [comment]
https://github.com/eGovFramework/egovframe-template-simple-react

최초 관리자 계정 설정은 [ 로그인계정 : admin , 로그인암호 : 1 ] 로 설정되어 있습니다.
해당 repository의 Read.me를 참고 부탁 드립니다.

**Comment by Chung10Kr** [comment]
아이고 프론트를 확인 못했네요 
감사합니다.
