### ISSUE TITLE
[Bug]: wiki 페이지 관리 문의

### ISSUE THREAD

**Issue by Chung10Kr** [eGovFramework/egovframe-template-simple-backend#28]
### 연락처 Contact

coohg93@hanmail.net

### 오류 내용 Error Description

![image](https://github.com/eGovFramework/egovframe-template-simple-backend/assets/30648191/81f4abb0-320a-4bb7-b03a-3b25637d7be4)

wiki 관련 문서 추가, 수정을 진행하려고 하는데

가이드에 나와있는것 처럼 New Page 버튼이 없습니다.

확인 부탁드립니다.

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 Operating System: 
 - 표준프레임워크 버전 eGovFrame Version: 
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

**Comment by eGovFrameSupport** [comment]
안녕하세요. 표준프레임워크 센터입니다.
질의 주신 페이지 설정을 수정하였으므로 확인 부탁 드립니다.

표준프레임워크 컨트리뷰션에 관심을 가져 주셔서 대단히 감사드립니다.

**Comment by Chung10Kr** [comment]
감사합니다.
