### ISSUE TITLE
[기능요구(Feature)]: Pull Requests 관련 문의 

### ISSUE THREAD

**Issue by Chung10Kr** [eGovFramework/egovframe-template-simple-backend#38]
### 연락처 Contact

coohg93@hanmail.net

### 추가 요청 기능명 Feature Name

 Pull Requests 관련 문의 

### 기능 상세 설명 Feature Description

현재 생성된  Pull Requests 중에 
Merge가 안된 상태로 오랜 시간 계류중 인것은 어떤 상태인지 알 수 있을까요?

**Comment by eGovFrameSupport** [comment]
https://github.com/eGovFramework/egovframe-template-simple-backend/pull/29 
-> 해당 PR은 테스트에만 사용되는 코드의 사용 건으로 Pending 상태입니다.

https://github.com/eGovFramework/egovframe-template-simple-backend/pull/37
-> 해당 PR은 내부 테스트 및 협의 중이며, 차주 중 merge 예정입니다.

표준프레임워크에 대한 지속적인 참여 및 관심에 대하여
대단히 감사드립니다.
